### PR TITLE
Created a client that uses callbacks for foreground jobs

### PR DESCRIPTION
**Pull request by agronick**
Hi your project was just what I was looking for except I wanted to consume the updates from Gearman as they came in rather than looping through the jobs and explicitly requesting updates. I made this client that will submit a group of jobs and allow the user to process the updates via a callback as they come in. The callback is called with UUIDs so the user doesn't need to worry about handles. This class works against what is in PIP right now. I think `job_data` might need to be changed for the new code. 

Hopefully this can help someone else. I just wanted to have it out there.

### CODE REVIEW

**Comment by sardok** [comment]
Thanks @agronick , merged.

**Comment by agronick** [comment]
Any idea when we'll see it in pip?

**Comment by sardok** [comment]
Just released as version 0.2.4.

**Comment by agronick** [comment]
Awesome

**Pull request merged**
